### ISSUE TITLE
Add OG and Twitter card information

### ISSUE THREAD

**Issue by ferblape** [PopulateTools/peticiones-abiertas#26]
Add Open Graph and Twitter card information in the header

**Comment by martgnz** [comment]
Maybe we can use [jekyll-seo](https://github.com/jekyll/jekyll-seo-tag), or is it overkill?

**Comment by ferblape** [comment]
A bit overkill, tags are there in the head, we just need to fill them up.

**Comment by martgnz** [comment]
Which image should we use for the meta tags? Do we have some kind of artwork?

Maybe the Populate logo.
